theme: jekyll-theme-minimal
lsi: false
safe: true
source: https://github.com/vsp-sign/MagApps
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge